### ISSUE TITLE
<else-if> support

### ISSUE THREAD

**Issue by vitalybe** [AlexGilleran/jsx-control-statements#15]
I often find the need to create an else if. The syntax to do currently is rather ugly:

    <If>
        // Condition
    </Else>
        <If>
            // First else if
        </Else>
            <If>
                // Second else if
            </Else>
                // Else (first level)
            </If>
        </If
    </If>

**Comment by AlexGilleran** [comment]
Yeah I usually find it's easier to create them all on one level and just keep `initialCondition &&` in the front of subsequent ifs.

The thing is that because `<If>` desugars into a ternary if there's not actually any easy way to do else if. We'd have to either make it so that what I said above was done automatically, or change it so `<If>` actually desugars into 

```
function() {
    if (cond1) {
         return x;
    } else if (cond2) {
        return y;
    } else {
        return z;
    }
}
```

**Comment by texttechne** [comment]
You can use the ternary operator for else if.
```
x ? x : ( y ? : z )
```

**Comment by AlexGilleran** [comment]
I'd say this is fulfilled by `<Choose>`
