### ISSUE TITLE
multiple elements in if/else

### ISSUE THREAD

**Issue by jdiaz5513** [AlexGilleran/jsx-control-statements#2]
There's a trick when using ternary expressions in JSX to have multiple adjacent elements by returning an array.

What I'd like to be able to see is for this...

```javascript
<If condition={something}>
  <p>Hello</p>
  <p>World</p>
</If>
```

to get transpiled into this...

```javascript
{something ?
  [
    <p>Hello</p>,
    <p>World</p>
  ]
  : ''
}
```

Of course it has the same issue as the `<For>` block (cannot be the root of a component) but I say this would be a worthwhile addition to the transform.

**Comment by AlexGilleran** [comment]
Yeah that's a good idea, will be even neater and shouldn't be too much harder :).

**Comment by jsfb** [comment]
It's potentially a little more difficult/complex than you might be imagining.  The main issue being that the following is not transformable:
```
render: function() { return <If condition={true}><p>Hello</p><p>World</p></If>; }
```

Because render is not allowed to return an array.  But because a jsx expression can be saved into a variable (with which, you could later decide to do anything - like insert into another element (legal) or return it (illegal)), it becomes literally impossible make the legal/illegal decision at transform time.  You would need to be exceedingly conservative (which would confuse users, who don't understand why sometimes the transform allows it and other times it doesn't) or add complicated runtime logic.

If I were you, I would just close this issue as "too difficult" and focus your efforts on lower hanging fruit.  There are a bunch of things you could do to make this transform totally awesome!  Eventually, we might support ReactFragment (https://github.com/reactjs/react-future/blob/0d451abb6e4ee1078d6761adda8a5247cbde1218/08%20-%20Types/01%20-%20Elements.js) which would make this more readily solvable.  When ReactFragment is supported, we might automatically wrap adjacent jsx tags in a fragment anyway, so this problem might be solved in a later version of jsx without you doing anything.

**Comment by AlexGilleran** [comment]
On reflection I'm going to take @jimfb's advice and leave this - as he says it's a lot simpler to just have the rule that a control statement contains a single element and have a single check for that at transform time, rather than an error-prone set of this-works-unless-this that are more confusing for the user.

**Comment by mwiencek** [comment]
Hmm, this is a tricky issue, but I think it'd be more useful and less confusing if fixed. :)

My mental concept of `<If>` is just that it evaluates the condition and outputs the children if true, not that it's an actual element that gets included on the page. So anyone who understands that `render` can't output multiple children should clearly understand that `render: function() { return <If condition={true}><p>Hello</p><p>World</p></If>; }` is wrong, IMO.

ReactFragment sounds cool, but also sounds like a long-term development that isn't coming soon. And when it does, a future version of jsx-control-statements could still support it.

So without fixing this, there's not really any good alternative besides adding a container `<div>` or multiple `<If>`s. Although if #16 is fixed we could output an array inside a JSX expression.

My only problem with having the plugin output an array is that you'd have to assign a `key` to each element, which wouldn't be obvious, because the array would be a hidden implementation detail. I think this plugin could be clever, though, and not use an array at all:

```
<If condition={true}>
  <p>Hello</p>
  <p>World</p>
</If>
```

Could possibly become:

```
{_prevConditions.push(_condition) && (_condition=!!(true)) && undefined}
{_condition && <p>Hello</p>}
{_condition && <p>World</p>}
{(_condition=_prevConditions.pop()) && undefined}
```

`_prevConditions` would solve the problem of nested `<If>`s, I think. Only problem would be, you'd need to hoist declarations for these temporary variables into the containing function (and pick names for them). Then you'd have to figure out how to deal with `<Else />`.

Anyway, these are just ideas I had which may or may not be reasonable, sorry for spamming an old issue :)

**Comment by AlexGilleran** [comment]
Definitely happy to hear ideas :)

**Comment by texttechne** [comment]
> My mental concept of <If> is just that it evaluates the condition and outputs the children if true, not that it's an actual element that gets included on the page. So anyone who understands that render can't output multiple children should clearly understand that `render: function() { return <If condition={true}><p>Hello</p><p>World</p></If>; }` is wrong, IMO.

Totally agree with @mwiencek. But we would need to make sure to warn about these cases explicitly in the docs, which we should do for the `<For>` statement as well.  

To check:
- How to implement a smart key generation?
- additional exception handling necessary for root elements?
